apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: split-infer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/hostname: controlplane
      containers:
        - name: server
          image: minhbui1/server-infer
          command: ["sh", "-c", "sleep 15 && python -u server.py"]
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: split-infer-config