name: YOLO
server:
  cut-layer: a #or b, c
  clients:
    - 2
    - 1
  model: yolov8n
  batch-frame: 20
  save-output: False
rabbit:
  address: 192.168.10.130
  username: admin
  password: admin
  virtual-host: /

data: video.mp4
log-path: logs
control-count: 10
debug-mode: False

imgsz: 320  