version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ main port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ../../rabbitmq-config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ../../rabbitmq-config/limits.conf:/etc/security/limits.conf
    networks:
      - SI-network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2GB"

  server:
    image: minhbui1/server-infer
    container_name: server
    depends_on:
      - rabbitmq
    volumes:
      - ../../configs/config.yaml:/app/config.yaml  
      - ../../logs:/app/logs
    networks:
      - SI-network
    command: ["sh", "-c", "sleep 5 && python -u server.py"]


  client11:
    image: minhbui1/client-infer:latest
    container_name: client11
    depends_on:
      - server
    volumes:
      - ../../configs/config.yaml:/app/config.yaml  
      - ../../logs:/app/logs
    networks:
      - SI-network
    command: ["sh", "-c", "sleep 10 && python client.py --layer_id 1 --device cpu"]
    deploy:
      resources:
        limits:
          cpus: "6"
          memory: "4GB"
  # client12:
  #   image: minhbui1/client-infer:latest
  #   container_name: client12
  #   depends_on:
  #     - server
  #   volumes:
  #    - ../../configs/config.yaml:/app/config.yaml  
  #    - ../../logs:/app/logs
  #   networks:
  #     - SI-network
  #   command: ["sh", "-c", "sleep 10 && python client.py --layer_id 1 --device cpu"]
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "3"
  #         memory: "3GB"


  client21:
    image: minhbui1/client-infer:latest
    container_name: client21
    depends_on:
      - server
    volumes:
      - ../../configs/config.yaml:/app/config.yaml  
      - ../../logs:/app/logs
    networks:
      - SI-network
    command: ["sh", "-c", "sleep 10 && python client.py --layer_id 2 --device cpu"]
    deploy:
      resources:
        limits:
          cpus: "6"
          memory: "4GB"

  # client22:
  #   image: minhbui1/client-infer:latest
  #   container_name: client22
  #   depends_on:
  #     - server
  #   volumes:
  #     - ./config.yaml:/app/config.yaml  
  #     - ./logs:/app/logs
  #   networks:
  #     - SI-network
  #   command: ["sh", "-c", "sleep 5 && python client.py --layer_id 2 --device cpu"]
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "3"
  #         memory: "3GB"


volumes:
  rabbitmq_data:

networks:
  SI-network:
    driver: bridge