version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ main port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ../../rabbitmq-config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ../../rabbitmq-config/limits.conf:/etc/security/limits.conf
    networks:
      - SI-network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "3GB"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - SI-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "5GB"
  server:
    image: minhbui1/server-infer:v2.0
    container_name: server
    depends_on:
      - rabbitmq
    volumes:
      - ../../configs/config.yaml:/app/config.yaml  
      - ../../logs:/app/logs
    networks:
      - SI-network
    command: ["sh", "-c", "sleep 5 && python -u server.py --config config.yaml"]


  client11:
    image: minhbui1/client-infer:v2.0
    container_name: client11
    # depends_on:
    #   - server
    volumes:
      - ../../configs/config.yaml:/app/config.yaml  
      - ../../logs:/app/logs
      - ../../videos/video.mp4:/app/video.mp4
    networks:
      - SI-network
    command: ["sh", "-c", "sleep 10 && python client.py --layer_id 1 --device cpu --config config.yaml"]
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4GB"
  # client12:
  #   image: minhbui1/client-infer:v2.0
  #   container_name: client12
  #   # depends_on:
  #   #   - server
  #   volumes:
  #     - ../../configs/config.yaml:/app/config.yaml  
  #     - ../../logs:/app/logs
  #     - ../../videos/video.mp4:/app/video.mp4
  #   networks:
  #     - SI-network
  #   command: ["sh", "-c", "sleep 10 && python client.py --layer_id 1 --device cpu --config config.yaml"]
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "5"
  #         memory: "4GB"

  client21:
    image: minhbui1/client-infer:v2.0
    container_name: client21
    depends_on:
      - server
    volumes:
      - ../../configs/config.yaml:/app/config.yaml  
      - ../../logs:/app/logs
      - ../../videos/video.mp4:/app/video.mp4
    networks:
      - SI-network
    command: ["sh", "-c", "sleep 10 && python client.py --layer_id 2 --device cpu --config config.yaml"]
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4GB"


volumes:
  rabbitmq_data:
  redis_data:

networks:
  SI-network:
    driver: bridge